Add concurrency to image creation
sindresorhus/pageres pull request #404
Opened 2021-01-06 04:18 UTC by shannonrothe

Noticed the comment so utilised `Promise.all()` to add concurrency to image creation 👍🏼

2021-01-06 18:37 UTC, sindresorhus commented
I don't think Puppeteer can handle a load like this. I think you need to use https://github.com/sindresorhus/p-all with a concurrency of maybe "number of CPUs * 2". Needs to be tested what gives the output performance.

2021-01-07 11:29 UTC, shannonrothe commented
@sindresorhus no problem, I might look into this a bit more when I get a chance 👍

2021-03-07 10:52 UTC, sindresorhus commented
Friendly bump :)

2021-03-07 23:59 UTC, shannonrothe commented
@sindresorhus still failing tests, not sure what the issue is with `p-all` 😕

2021-03-08 06:18 UTC, sindresorhus commented
You are using `p-all` incorrectly, which the error also points out.

2021-03-08 06:19 UTC, sindresorhus commented
It might be better to use `p-map` since you're mapping `this.sizes`.

2021-03-08 10:08 UTC, shannonrothe commented
> It might be better to use `p-map` since you're mapping `this.sizes`.

Done, should be okay now 👌🏼

2021-03-08 10:39 UTC, sindresorhus requested changes

2021-03-08 10:39 UTC, sindresorhus commented on source/index.ts
> +			this.items.push(...await pMap(
This is not very readable. Make it a variable and then in a new statement, you can use destructuring instead of "push".

2021-03-08 10:39 UTC, sindresorhus commented on .gitignore
> +.vscode/
These should be in your own global gitignore, not here.

2021-03-08 12:26 UTC, merged

2021-03-08 12:26 UTC, sindresorhus commented
Thanks :)